-- 1. Assets Table (Ticker Mapping)
CREATE TABLE public.assets (
    symbol varchar(50) PRIMARY KEY, -- Our internal ID (e.g., BTC-USD, TSLA)
    api_id varchar(100) NOT NULL,   -- External API ID (e.g., bitcoin, TSLA)
    asset_type varchar(20) NOT NULL, -- CRYPTO, STOCK
    is_active boolean DEFAULT true,   -- Switch to enable/disable collection
    created_at timestamptz DEFAULT now()
);

-- Initial Data for Assets
INSERT INTO public.assets (symbol, api_id, asset_type) VALUES
-- Cryptocurrencies
('BTC-USD', 'BTC-USD', 'CRYPTO'), -- yahoo-finance uses BTC-USD
('ETH-USD', 'ETH-USD', 'CRYPTO'),
('SOL-USD', 'SOL-USD', 'CRYPTO'),
('XRP-USD', 'XRP-USD', 'CRYPTO'),
('DOGE-USD', 'DOGE-USD', 'CRYPTO'),
-- US Stocks
('TSLA', 'TSLA', 'STOCK'),
('NVDA', 'NVDA', 'STOCK'),
('AAPL', 'AAPL', 'STOCK'),
('MSFT', 'MSFT', 'STOCK'),
('TQQQ', 'TQQQ', 'STOCK'),
('SQQQ', 'SQQQ', 'STOCK'),
-- KR Stocks (examples)
('005930.KS', '005930.KS', 'STOCK'), -- Samsung Electronics
('000660.KS', '000660.KS', 'STOCK'); -- SK Hynix

-- 2. Market Prices Table
CREATE TABLE public.market_prices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_symbol varchar(50) NOT NULL REFERENCES public.assets(symbol), -- Foreign key for integrity
    price numeric NOT NULL,
    recorded_at timestamptz DEFAULT now(),
    
    -- Ensure unique price per ticker per timestamp to avoid duplicates
    CONSTRAINT market_prices_unique_entry UNIQUE (ticker_symbol, recorded_at)
);

-- Index for fast lookup by ticker and time
CREATE INDEX idx_market_prices_search ON public.market_prices (ticker_symbol, recorded_at DESC);
